kind: Deployment
apiVersion: apps/v1
metadata:
  name: pokemon-list-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-list
  template:
    metadata:
      labels:
        app: pokemon-list
    spec:
      containers:
        - name: pokemon-list
          image: pokemonlistacr.azurecr.io/pokemon
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: pokemon-list