name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        branch: main
        service_principal: ${{ secrets.SP }}
        service_principal_password: ${{ secrets.SP_PASSWORD }}
        tenant: ${{ secrets.SP_TENANT }}
        registry: ${{ secrets.REGISTRY }}
        repository: ${{ secrets.REPOSITORY }}
        image: image
        folder: ./
        dockerfile: ./dockerfile
