name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
#     - name: Microsoft Azure Container Registry Login
#       uses: elgohr/acr-login-action@0.1
#       with:
#         service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
#         service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PASSWARD }}
#         tenant: ${{ secrets.AZURE_TENANT_ID }}
#         registry: pokemonlistacr.azurecr.io
#         repository: pokemon


    - name: Azure Container Registry Build
      uses: Azure/acr-build@v1
      with:
        branch: main
        service_principal: ${{ secrets.SP }}
        service_principal_password: ${{ secrets.SP_PASSWORD }}
        tenant: ${{ secrets.SP_TENANT }}
        registry: REGISTRY
        repository: REPOSITORY
        image: image
        folder: src/
        dockerfile: ../dockerfile


        
